### ISSUE TITLE
Process to run ?

### ISSUE THREAD

**Issue by areddy7021** [ayman-elgharabawy/Kafka-SpringBoot-WebSocket#1]
Hi , 

It's really awesome tutorial on everything which i really like but can you please post out the process to how to run the application and test out the exact scanarios ?

Thanks,
Akhil.

**Comment by samueledirito** [comment]
You need to run `docker-compose up` to create the containers.

**Comment by mostafa-eltaher** [comment]
Can you recheck the DZone article, we have updated it with the build and run steps.

**Comment by areddy7021** [comment]
thank you..it's really cool now. Thank You very much.
