### ISSUE TITLE
Docker build command not working ?

### ISSUE THREAD

**Issue by areddy7021** [ayman-elgharabawy/Kafka-SpringBoot-WebSocket#2]
Hi , 

I am facing an issue with the docker build command. docker build microsvc-angular/static-web AngularDocker/. I am on windows box .

I am doing that on project folder.

Thanks,
Akhil

**Comment by mostafa-eltaher** [comment]
Sorry, the command is missing **-t**, the full command is `docker build -t microsvc-angular/static-web AngularDocker/`
